name: compile-project
run-name: Compile project using Actionfile

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
  pull_request: {}


jobs:
  test-compile-project:
    runs-on: ubuntu-latest

    steps:
      - name: Enable linger and create user session (workaround)
        uses: gbraad-actions/blacksmith-user-session@main

      - name: Allow unprivileged userns (workaround)
        uses: gbraad-actions/warpbuild-unprivileged-userns@main

      - name: Checkout gstow repo
        uses: actions/checkout@v6

      - name: Setup action tool from releases
        uses: ducttape-infra/actionfile-install-action@v0.6

      - name: Run build action
        run: |
          action build local

